[Rainmeter]
Update=1000
DynamicWindowSize=1
DynamicVariables=1

[Variables]
SITEURL=https://animeav1.com

; RegExp made simple

UploadTime=<span class="from-soft text-subs absolute.*>(.*)</span>
EpisodeNum=.*<span class="text-lead font-bold">(.*)</span>
AnimeName=.*<div class="text-2xs text-subs font-bold uppercase">(.*)</div>
AnimeHREF=.*<a class="absolute inset-0 z-20 grid place-content-center" href="(.*)">
SubstituteFeed="&#39;":"'","&amp;":"&","&quot;":'"',"&lt;":"<","&gt;":">"
Data=#UploadTime##EpisodeNum##AnimeName##AnimeHREF#

WidgetSizeX=370
WidgetSizeY=105
WidgetInteriorOffsetX=1
WidgetInteriorOffsetY=1
ForeGroundSizeY=25
ForeGround2SizeY=26

Font=JetBrains Mono

TabsMaxSize=2
TabsCurrentPosition=1

BackgroundColor=0,0,0,220
BackgroundPositionY=0
BackgroundPositionX=0
ForegroundColor1=255,255,255,65
ForegroundColor2=255,255,255,40
ForeGroundRelativeSpacingY=26r

FirstLineX=20
FirstLineY=0
FirstLineRelativeSpacingY=26r
FirstLineFontSize=9
FirstLineFontWeight=0
FirstLineFontColor=0,255,255,255
FirstLineFontBorderColor=0,0,0,255

SecondLineY=13
SecondLineItem1X=#FirstLineX#
SecondLineItem2X=(160+#FirstLineX#)
SecondLineRelativeSpacingY=26r
SecondLineFontSize=8
SecondLineFontWeight=0
SecondLineLabelFontColor=255,255,255,255
SecondLineFontColor=255,0,255,255
SecondLineFontBorderColor=0,0,0,255

BulletCoordinatesX=6
BulletCoordinatesY=(#WidgetInteriorOffsetY#+8)
BulletPointMouseOverOn=255,0,255,255
BulletPointMouseOverOff=255,255,255,255
BulletPointBorderColor=0,0,0,255
BulletPointShape=Rectangle 0,0,7,7,2,2
BulletPointBorderWidth=2
BulletPointRelativeSpacingY=26r

---------------------------------------------------------------------

;-- Fuentes de Informacion

[AnimeInfo]
Measure=Plugin
Plugin=Plugins\WebParser.dll
UpdateRate=#Update#
Url=#SITEURL#
RegExp=(?siU)#Data#.*#Data#.*#Data#.*#Data#
RegExpSubstitute=1
Substitute=#SubstituteFeed#

---------------------------------------------------------------------

;-- Measure Block 

[AnimeURL1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=4
Substitute=#SubstituteFeed#
[AnimeURL2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=8
Substitute=#SubstituteFeed#
[AnimeURL3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=12
Substitute=#SubstituteFeed#
[AnimeURL4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=16
Substitute=#SubstituteFeed#

--

[AnimeName1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=3
Substitute=#SubstituteFeed#
[AnimeName2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=7
Substitute=#SubstituteFeed#
[AnimeName3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=11
Substitute=#SubstituteFeed#
[AnimeName4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=15
Substitute=#SubstituteFeed#

--

[AnimeTitle1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=2
Substitute=#SubstituteFeed#
[AnimeTitle2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=6
Substitute=#SubstituteFeed#
[AnimeTitle3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=10
Substitute=#SubstituteFeed#
[AnimeTitle4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=14
Substitute=#SubstituteFeed#

---

[AnimeReleaseDate1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=1
Substitute=#SubstituteFeed#
[AnimeReleaseDate2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=5
Substitute=#SubstituteFeed#
[AnimeReleaseDate3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=9
Substitute=#SubstituteFeed#
[AnimeReleaseDate4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[AnimeInfo]
StringIndex=13
Substitute=#SubstituteFeed#


---------------------------------------------------------------------

;-- Begining: Construccion del Widget

;-- Widget container

[BG]
Meter=Image
x=#BackgroundPositionX#
y=#BackgroundPositionY#
h=#WidgetSizeY#
w=#WidgetSizeX#
Solidcolor=#BackgroundColor#

;- Container for information

[FG1]
Meter=Image
x=#WidgetInteriorOffsetX#
y=#WidgetInteriorOffsetY#
h=#ForeGroundSizeY#
w=(#WidgetSizeX#-2*#WidgetInteriorOffsetX#)
Solidcolor=#ForegroundColor1#
[FG2]
Meter=Image
x=#WidgetInteriorOffsetX#
y=(#ForeGround2SizeY#+#WidgetInteriorOffsetY#)
h=#ForeGroundSizeY#
w=(#WidgetSizeX#-2*#WidgetInteriorOffsetX#)
Solidcolor=#ForegroundColor2#
[FG3]
Meter=Image
MeterStyle=FG1
y=#ForeGroundRelativeSpacingY#
[FG4]
Meter=Image
MeterStyle=FG2
y=#ForeGroundRelativeSpacingY#

;-- Bullets points for Anime Links

[Rect]
Meter=Shape
y=#BulletCoordinatesY#
x=#BulletCoordinatesX#
Shape=#BulletPointShape# | Extend MySharedModifiers
MySharedModifiers=Fill Color #BulletPointMouseOverOff# | StrokeWidth #BulletPointBorderWidth# | Stroke Color #BulletPointBorderColor#
LeftMouseUpAction=["#SITEURL#[AnimeURL1]"]
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "#BulletPointShape# | Fill Color #BulletPointMouseOverOn# | StrokeWidth #BulletPointBorderWidth# | Stroke Color #BulletPointBorderColor#"][!UpdateMeter "#CURRENTSECTION#"][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "#BulletPointShape# | Fill Color #BulletPointMouseOverOff# | StrokeWidth #BulletPointBorderWidth# | Stroke Color #BulletPointBorderColor#"][!UpdateMeter "#CURRENTSECTION#"][!Redraw]
DynamicVariables=1
ClipString=1
AntiAlias=1

[Rect2]
Meter=Shape
y=#BulletPointRelativeSpacingY#
LeftMouseUpAction=["#SITEURL#[AnimeURL2]"]
MeterStyle=Rect
[Rect3]
Meter=Shape
y=#BulletPointRelativeSpacingY#
LeftMouseUpAction=["#SITEURL#[AnimeURL3]"]
MeterStyle=Rect
[Rect4]
Meter=Shape
y=#BulletPointRelativeSpacingY#
LeftMouseUpAction=["#SITEURL#[AnimeURL4]"]
MeterStyle=Rect

;-- Anime Name and Episode Number

[MeterName1]
MeasureName=AnimeName1
Meter=STRING
X=#FirstLineX#
Y=#FirstLineY#
W=(#WidgetSizeX#-30*#WidgetInteriorOffsetX#)
FontWeight=950
StringEffect=Border
FontEffectColor=#FirstLineFontBorderColor#
FontColor=#FirstLineFontColor#
FontSize=#FirstLineFontSize#
StringAlign=LeftTop
FontFace=#Font#
Antialias=1
ClipString=1

[MeterName2]
MeasureName=AnimeName2
Meter=STRING
Y=#FirstLineRelativeSpacingY#
MeterStyle=MeterName1
[MeterName3]
MeasureName=AnimeName3
Meter=STRING
Y=#FirstLineRelativeSpacingY#
MeterStyle=MeterName1
[MeterName4]
MeasureName=AnimeName4
Meter=STRING
Y=#FirstLineRelativeSpacingY#
MeterStyle=MeterName1

; -- Reselease Date

[MeterDate1]
MeasureName=AnimeReleaseDate1
Meter=STRING
X=#SecondLineItem1X#
Y=#SecondLineY#
StringCase=Proper
FontWeight=500
StringEffect=Border
FontEffectColor=#SecondLineFontBorderColor#
FontColor=#SecondLineFontColor#
FontSize=#SecondLineFontSize#
StringAlign=LEFT
FontFace=#Font#
Antialias=1
InlineSetting=Color | #SecondLineLabelFontColor#
InlinePattern=Date:
Prefix="Date:"

[MeterDate2]
MeasureName=AnimeReleaseDate2
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterDate1
[MeterDate3]
MeasureName=AnimeReleaseDate3
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterDate1
[MeterDate4]
MeasureName=AnimeReleaseDate4
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterDate1

; -- Chapter Title

[MeterTitle1]
MeasureName=AnimeTitle1
Meter=STRING
X=#SecondLineItem2X#
Y=#SecondLineY#
FontWeight=500
StringEffect=Border
FontEffectColor=#SecondLineFontBorderColor#
FontColor=#SecondLineFontColor#
FontSize=#SecondLineFontSize#
StringAlign=LEFT
FontFace=#Font#
Antialias=1
InlineSetting=Color | #SecondLineLabelFontColor#
InlinePattern=Episode:
Text=Episode:%1
DynamicVariables=1

[MeterTitle2]
MeasureName=AnimeTitle2
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterTitle1
[MeterTitle3]
MeasureName=AnimeTitle3
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterTitle1
[MeterTitle4]
MeasureName=AnimeTitle4
Meter=STRING
Y=#SecondLineRelativeSpacingY#
MeterStyle=MeterTitle1

;-- EOF
