[Rainmeter]
Update=1000
DynamicWindowSize=1

[Variables]
SITEURL=https://tcbonepiecechapters.com

MangaHref=<a class="text-white text-lg font-bold" href="(.*)".*>
MangaName=.*(.*)</a>
MangaChapter=.*<div>(.*)</div>
DateUpdate=.*<time-ago.*>(.*)</time-ago>
SubstituteFeed="&#39;":"'","&amp;":"&","&quot;":'"',"&lt;":"<","&gt;":">"
Data=#MangaHref##MangaName##MangaChapter##DateUpdate#

Font=JetBrains Mono
FL_FontColor=255,0,255,255
SL_FontColor=0,255,255,255

FirstLineFontSize=9
FirstLineX=20
FirstLineY=0
FL_RelativeSpacingY=26r

SecondLineFontSize=8
SecondLineItem1X=#FirstLineX#
SecondLineItem2X=(105+#SecondLineItem1X#)
SecondLineY=13
SL_RelativeSpacingY=26r

WidgetSizeX=370
WidgetSizeY=105
WidgetInteriorOffsetX=1
WidgetInteriorOffsetY=1
ForeGround2SizeY=26
ForeGroundSizeY=25

[TCBScans]
Measure=Plugin
Plugin=Plugins\WebParser.dll
UpdateRate=1000
Url=#SITEURL#
RegExp=(?siU)#Data#.*#Data#.*#Data#.*#Data#
RegExpSubstitute=1
Substitute=#SubstituteFeed#

[BG]
Meter=Image
x=0
y=0
h=#WidgetSizeY#
w=#WidgetSizeX#
Solidcolor=0,0,0,220

[FG1]
Meter=Image
x=#WidgetInteriorOffsetX#
y=#WidgetInteriorOffsetY#
h=#ForeGroundSizeY#
w=(#WidgetSizeX#-2*#WidgetInteriorOffsetX#)
Solidcolor=255,255,255,65

[FG2]
Meter=Image
x=#WidgetInteriorOffsetX#
y=(#ForeGround2SizeY#+#WidgetInteriorOffsetY#)
h=#ForeGroundSizeY#
w=(#WidgetSizeX#-2*#WidgetInteriorOffsetX#)
Solidcolor=255,255,255,40

[FG3]
Meter=Image
MeterStyle=FG1
y=26r

[FG4]
Meter=Image
MeterStyle=FG2
y=26r

[Rect]
Meter=Shape
y=(#WidgetInteriorOffsetY#+8)
x=6
Shape=Rectangle 0,0,7,7,2,2 | Extend MySharedModifiers
MySharedModifiers=Fill Color 255,255,255,255 | StrokeWidth 2 | Stroke Color 0,0,0,255
LeftMouseUpAction=["#SITEURL#[MangaURL1]"]
DynamicVariables=1
ClipString=1
AntiAlias=1

[Rect2]
Meter=Shape
y=26r
LeftMouseUpAction=["#SITEURL#[MangaURL2]"]
MeterStyle=Rect
[Rect3]
Meter=Shape
y=26r
LeftMouseUpAction=["#SITEURL#[MangaURL3]"]
MeterStyle=Rect
[Rect4]
Meter=Shape
y=26r
LeftMouseUpAction=["#SITEURL#[MangaURL4]"]
MeterStyle=Rect


---------------------------------------

[MangaURL1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=1
Substitute=#SubstituteFeed#
[MangaURL2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=5
Substitute=#SubstituteFeed#
[MangaURL3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=9
Substitute=#SubstituteFeed#
[MangaURL4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=13
Substitute=#SubstituteFeed#

--

[MangaNameChapNum1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=2
Substitute=#SubstituteFeed#
[MangaNameChapNum2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=6
Substitute=#SubstituteFeed#
[MangaNameChapNum3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=10
Substitute=#SubstituteFeed#
[MangaNameChapNum4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=14
Substitute=#SubstituteFeed#

--

[MangaTitle1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=3
Substitute=#SubstituteFeed#
[MangaTitle2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=7
Substitute=#SubstituteFeed#
[MangaTitle3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=11
Substitute=#SubstituteFeed#
[MangaTitle4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=15
Substitute=#SubstituteFeed#

---

[MangaReleaseDate1]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=4
Substitute=#SubstituteFeed#
[MangaReleaseDate2]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=8
Substitute=#SubstituteFeed#
[MangaReleaseDate3]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=12
Substitute=#SubstituteFeed#
[MangaReleaseDate4]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[TCBScans]
StringIndex=16
Substitute=#SubstituteFeed#

----------------------------

;-- Manga Name and Chapter Number

[MeterName1]
MeasureName=MangaNameChapNum1
Meter=STRING
X=#FirstLineX#
Y=#FirstLineY#
FontWeight=950
StringEffect=Border
FontEffectColor=0,0,0,255
FontColor=#FL_FontColor#
FontSize=#FirstLineFontSize#
StringAlign=LeftTop
FontFace=#Font#
Antialias=1

[MeterName2]
MeasureName=MangaNameChapNum2
Meter=STRING
Y=#FL_RelativeSpacingY#
MeterStyle=MeterName1

[MeterName3]
MeasureName=MangaNameChapNum3
Meter=STRING
Y=#FL_RelativeSpacingY#
MeterStyle=MeterName1

[MeterName4]
MeasureName=MangaNameChapNum4
Meter=STRING
Y=#FL_RelativeSpacingY#
MeterStyle=MeterName1

; -- Chapter Title

[MeterTitle1]
MeasureName=MangaTitle1
Meter=STRING
X=#SecondLineItem2X#
Y=#SecondLineY#
FontWeight=500
StringEffect=Border
FontEffectColor=0,0,0,255
FontColor=#SL_FontColor#
FontSize=#SecondLineFontSize#
StringAlign=LEFT
FontFace=#Font#
Antialias=1
InlineSetting=Color | 255,255,255,255
InlinePattern=Title:
Text=Title:%1
;Prefix="Title:"

[MeterTitle2]
MeasureName=MangaTitle2
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterTitle1

[MeterTitle3]
MeasureName=MangaTitle3
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterTitle1

[MeterTitle4]
MeasureName=MangaTitle4
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterTitle1

; -- Reselease Date

[MeterDate1]
MeasureName=MangaReleaseDate1
Meter=STRING
X=#SecondLineItem1X#
Y=#SecondLineY#
FontWeight=500
StringEffect=Border
FontEffectColor=0,0,0,255
FontColor=#SL_FontColor#
FontSize=#SecondLineFontSize#
StringAlign=LEFT
FontFace=#Font#
Antialias=1
InlineSetting=Color | 255,255,255,255
InlinePattern=Date:
Prefix="Date:"

[MeterDate2]
MeasureName=MangaReleaseDate2
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterDate1

[MeterDate3]
MeasureName=MangaReleaseDate3
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterDate1

[MeterDate4]
MeasureName=MangaReleaseDate4
Meter=STRING
Y=#SL_RelativeSpacingY#
MeterStyle=MeterDate1

;--

